### ISSUE TITLE
`esh` does not honor the umask value of its parent process when using the `-o` option

### ISSUE THREAD

**Issue by nclsgd** [jirutka/esh#12]
Hi!
First of all, kudos for this great little template engine! The attention to portability and correctness is really appreciated. 👏

I stumbled upon a little issue today as I was using the `-o` option: I realized that `esh` does not honor the umask value of its parent process and always produces files with the UNIX mode `u+rw` (0600) as the file is created by `mktemp` and not by `esh` itself:
https://github.com/jirutka/esh/blob/4f1bc6e831aad27a2016977743ed1ad3042385b6/esh#L360-L363

This behavior can cause bugs in situations where the output file mode is expected to be something like `rw-r--r--` (i.e. with the common and default `0022` umask value).
I think that replacing the `mv` command with something like `cat "$tmpfile" > "$OUTPUT"` should fix this.

---

On another note (not related to the issue above but I've realized this when reading the code), I think that the following line:
https://github.com/jirutka/esh/blob/4f1bc6e831aad27a2016977743ed1ad3042385b6/esh#L361

would be safer with the quotation marks (the single and double quotes) placed the other way around (and also because the `$tmpfile` variable seems to be always set on the occasions where the trap command would be triggered).

In a quite twisted scenario (i.e. where an adversary is able to create arbitrary directories in the filesystem *and* controlling the `TMPDIR` environment variable exposed to `esh` using the `-o` option) the trap command would then be vulnerable to a shell injection attack.

**Comment by jirutka** [comment]
I’ve fixed both issues. Thanks for your advice!
