### ISSUE TITLE
feature request: include once

### ISSUE THREAD

**Issue by andreineculau** [jirutka/esh#13]
While it should be possible to implement the logic for include-once with the current functionality,
I'm wondering if you have thought of having that functionality built-in and if you'd accept a PR.

Thanks for creating esh btw ❗

**Comment by jirutka** [comment]
I don’t know what you mean by include-once; what should this feature do?

**Comment by andreineculau** [comment]
Apologies. Should have explained better.

Esh currently has "<%+" syntax to include to read and convert a template.

What I'm asking is about a "<%=1" or similar syntax where the template would only be read and converted once, thus leaving further references replaced with nothing.

--
http://andreineculau.com

**Comment by jirutka** [comment]
Could you please provide some example where such feature would be useful? I can’t imagine any.

**Comment by andreineculau** [comment]
An included file declares variables with default values, for example. It has side effects once could say.

* `foo.sh` = `FOO=1`
* `1.sh` = `<%+foo.sh%>; function foo() {echo 1 $FOO}`
* `2.sh` = `<%+foo.sh%>; FOO=2; <%+1.sh%>; foo`
 
The semantics of including `foo.sh` can be either "reset" (prints `1 1`) or "require" (prints `1 2`), where "require" would mean "I need a FOO variable defined somehow, but not necessarily set to 1".

My specific example is that I am working with grammars (specifically ABNF grammars from IETF RFCs). Many RFCs are not standalone, but rely on other RFC's grammars. Sometimes the order matters, sometimes the definitions are colliding. Being able to "require" instead of "reset" is essential to providing the means to change the order of such definitions and letting the "last" one win e.g.

```
# content of word.abnf
word = [A-Za-z]+

# content of sentence.abnf
<%= word.abnf %>
sentence = (word " ")* word

# content of word2.abnf
word = \w+
``` 

given the above, one can create

```
# content of sentence2.abnf
<%= word.abnf %>
<%= word2.abnf %>
<%= sentence.abnf %> // sentence.abnf requires word.abnf, but it is already required, so it is skipped, leaving word defined as in word2.abnf
```

Without the `<%=` syntax, `<%+` would "reset" word to its definition in word.abnf .

**Comment by jirutka** [comment]
I’m afraid you’re using esh for something it was never intended for. The main goal of esh is simplicity and this feature doesn’t look like something most people need. I’m sorry.

**Comment by andreineculau** [comment]
No need to be sorry. Thanks for closing.
