### ISSUE TITLE
Question/idea: escaping long or special arguments

### ISSUE THREAD

**Issue by agseco** [jirutka/esh#3]
Firstly, thanks for sharing this tool, I'm use ESH to generate SQL scripts from a template and it just works great :)

This is the shell script I'm using:

```
#!/bin/sh

ESH_VERSION=0.1.1
ESH_FILE_NAME=esh-${ESH_VERSION}
ESH_DOWNLOAD_FILE_NAME=${ESH_FILE_NAME}.tar.gz
ESH_DOWNLOAD_BASE_DIR=/tmp
ESH_DOWNLOAD_DIR=/tmp/${ESH_FILE_NAME}
ESH_DOWNLOAD_PATH=${ESH_DOWNLOAD_BASE_DIR}/${ESH_DOWNLOAD_FILE_NAME}
ESH_BIN=${ESH_DOWNLOAD_BASE_DIR}/${ESH_FILE_NAME}/esh

usage () { echo "Script usage: $(basename $0) -p prefix -c collection_name"; }

while getopts ':p:c:h' OPTION; do
  case "$OPTION" in
    p) PREFIX="$OPTARG";;
    c) COLLECTION="$OPTARG";;
    h) usage; >&2 exit 1;;
    :) echo "Invalid option: $OPTARG requires an argument" 1>&2;;
    ?) usage; >&2 exit 1;;
  esac
done
shift "$(($OPTIND -1))"

# Download ESH if it wasn't downloaded before
if [ ! -d "$ESH_DOWNLOAD_DIR" ]; then
  wget https://github.com/jirutka/esh/archive/v${ESH_VERSION}/${ESH_DOWNLOAD_FILE_NAME} -O ${ESH_DOWNLOAD_PATH}
  tar -xzf ${ESH_DOWNLOAD_PATH} -C ${ESH_DOWNLOAD_BASE_DIR}
fi

printf "/*\n"
printf "+------------------------------------------+\n"
printf "            Scripts start here\n"
printf "+------------------------------------------+\n"
printf "*/\n"
printf "\n"

${ESH_BIN} template.sql PREFIX=${PREFIX} COLLECTION=${COLLECTION}
printf "\n"

printf "\n"
printf "\n"

printf "/*\n"
printf "+------------------------------------------+\n"
printf "             Scripts end here\n"
printf "+------------------------------------------+\n"
printf "*/\n\n"
```

Probably not the best script, but I have to acknowledge the fact that I'm not very good at shell/bash scripting 😅

Usage example: `./script.sh -p zz -c replies`works just fine-

Now let's say I want to support an option `-f` whose argument is a set of table fields in the DDL script, for example: `./script.sh -p zz -c replies -f "my_field varchar(500) DEFAULT NULL"`

It would fail with: `esh: illegal argument: varchar(500)`

Is there a way to somehow escape a variable's value? If not, IMHO it would be a nice feature :)

Cheers.

**Comment by jirutka** [comment]
The problem is probably in the way you’re handling arguments in your script. There’s no `-f` option in the snippet you’ve posted, so cannot say more.

**Comment by agseco** [comment]
I solved it with `sed` in the end, thanks anyways :)
