### ISSUE TITLE
The same process that declared a variable will also report an error!

### ISSUE THREAD

**Issue by robertzhangwenjie** [jirutka/esh#7]
![image](https://user-images.githubusercontent.com/35749198/91975057-5f95ad00-ed51-11ea-887b-d92efa11cfd1.png)

nginx.tpl.esh
```
access_log <%= ${HOME}/nginx_access.log %> main;
    error_log <%= ${HOME}/error.lg %>;

    root <%= ${HOME}/APP_NAME %>; 

    <% if  [ -z "$location" ] || [ "${location}" == "/" ] && [ -n "$backend_url" ];then %>
    location / {
      proxy_pass <%= $backend_url %>;
      proxy_set_header Host $host;
    }
    <% fi %>
```
The same process that declared a variable will also report an error!

**Comment by jirutka** [comment]
You didn’t export these variables, so they cannot get into `esh` process, obviously. That’s how the shell works.

You can either pass the variables as arguments to `esh` (as explained in `--help`):

```sh
esh ./template/nginx.tpl.esh backend_url=1 location=2
```

or use shell’s feature to pass environment variables for a command:

```sh
backend_url=1 location=2 esh ./template/nginx.tpl.esh
```

or export variables before executing `esh`:


```sh
export backend_url=1
export location=2
esh ./template/nginx.tpl.esh
```
